// ui/src/widgets/student-course-view/ui/student-course-view.vue
<script setup lang="ts">
  import { AssignmentCard } from '@/entities/assignment';
  import { AssignmentLink } from '@/features/go-to-assignment';

  defineProps<{
    upcomingDeadlines: Array<{
      assignmentID: number;
      assignmentName: string;
      submissionDeadline: Date;
    }>;
    ungradedSubmissions: Array<{
      assignmentID: number;
      assignmentName: string;
      gradingDeadline: Date;
      gradingProgress: {
        totalStudents: number;
        submissions: number;
        gradedSubmissions: number;
      };
    }>;
  }>();
</script>

<template>
  <p class="mb-3 text-center font-medium">Upcoming deadlines</p>

  <AssignmentCard
    v-for="assignment in upcomingDeadlines"
    :key="assignment.assignmentID"
    :submissionDeadline="assignment.submissionDeadline"
  >
    <template v-slot:assignment-name>
      <AssignmentLink :id="assignment.assignmentID">
        {{ assignment.assignmentName }}
      </AssignmentLink>
    </template>
  </AssignmentCard>

  <p class="mt-6 mb-3 text-center font-medium">Ungraded submissions</p>

  <AssignmentCard
    v-for="assignment in ungradedSubmissions"
    :key="assignment.assignmentID"
    :gradingDeadline="assignment.gradingDeadline"
    :gradingProgress="assignment.gradingProgress"
  >
    <template v-slot:assignment-name>
      <AssignmentLink :id="assignment.assignmentID">
        {{ assignment.assignmentName }}
      </AssignmentLink>
    </template>
  </AssignmentCard>
</template>

// ui/src/widgets/student-course-view/ui/student-course-view.svelte
<script lang="ts">
  import { AssignmentCard } from '@/entities/assignment';
  import { AssignmentLink } from '@/features/go-to-assignment';
  import type { UpcomingDeadline, UngradedSubmission } from '@/shared/api';

  export let upcomingDeadlines: UpcomingDeadline[];
  export let ungradedSubmissions: UngradedSubmission[];
</script>

<p class="mb-3 text-center font-medium">Upcoming deadlines</p>

{#each upcomingDeadlines as assignment (assignment.assignmentID)}
  <AssignmentCard
    submissionDeadline={assignment.submissionDeadline}
  >
    <svelte:fragment slot="assignment-name">
      <AssignmentLink id={assignment.assignmentID}>
        {assignment.assignmentName}
      </AssignmentLink>
    </svelte:fragment>
  </AssignmentCard>
{/each}

<p class="mt-6 mb-3 text-center font-medium">Ungraded submissions</p>

{#each ungradedSubmissions as assignment (assignment.assignmentID)}
  <AssignmentCard
    gradingDeadline={assignment.gradingDeadline}
    gradingProgress={assignment.gradingProgress}
  >
    <svelte:fragment slot="assignment-name">
      <AssignmentLink id={assignment.assignmentID}>
        {assignment.assignmentName}
      </AssignmentLink>
    </svelte:fragment>
  </AssignmentCard>
{/each}
